### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by andreldm** [ahmubashshir/xfce4-panel-gtkpopover#1]
Hi, I tried to build the project but on Arch Linux (panel 4.14.3) I get:
`libxfce4panel-2.0.vapi:124.3-124.41: error: overriding method `Xfce.PanelPlugin.remote_event' is incompatible with base method `bool Xfce.PanelPluginProvider.remote_event (string, GLib.Value, uint)': too few parameters.`

While on Ubuntu 18.04 (panel 4.12.2):
`error: Package 'libxfce4panel-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories`

Can you please tell me which distro you're using and which packages you had to install or build from source?

**Comment by ahmubashshir** [comment]
I was using Manjaro Xfce 19.0.2 with panel 4.14.3, I'm also getting this error now.
I think this error is caused by outdated 'xfce4-vala' package.
btw, this won't compile in bionic because it uses xfce 4.12.

**Comment by andreldm** [comment]
I tried [xfce4-vala-git](https://aur.archlinux.org/packages/xfce4-vala-git/) from AUR but it doesn't even build. Xfce's support for Vala is for a long time unmaintained, if you're starting a new project I can't recommend you enough to write it in C (Unless you love Vala and Xfce enough to invest some time in making things functional again).

**Comment by andreldm** [comment]
Answering your question from stackoverflow: no, popovers won't work in Xfce panel plugins.
Take a look at this gist: https://gist.github.com/andreldm/83c9b99e7aa133c924fb4165acc8427a

The standalone app shows the popover correctly, but try making the window as small as the button, there is no room left for the popover, that's the same problem in a panel plugin. If I'm not mistaken context menu work because they are completely new windows while popover aren't.

In the same gist you can find a diff against [xfce4-sample-plugin](https://git.xfce.org/panel-plugins/xfce4-sample-plugin/) with code similar to this repository.

Let me know if the answer is satisfactory so I can post it at SO.

**Comment by ahmubashshir** [comment]
Thanks, you can post it at SO.
